In [2]:
import numpy as np

## Crear un vector con valores dentro del rango 10 a 49 (un vector con 40 valores que inicie en 10 y termine en 49)

In [12]:
arr=np.array(np.arange(10,50))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Invertir el vector anterior:

In [27]:
arr2=[]
count= (len(arr) -1)
a = count + 1

for i in range (0,a):
    s=arr[count]
    arr2.append(s)
    count =  count - 1
    
print(arr2)


[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


## Crear una matriz 3x3 con valores de 0 a 8

In [29]:
arr3=np.arange(9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [47]:
arr4=np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
arr5= np.array(arr4!=0)
arr4[arr5==True]


array([ 1,  2,  4,  2,  4,  1, 12,  4,  5,  6,  7])

## Crear una matriz identidad de 6x6

In [53]:
arr6= np.identity(6)
arr6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Crear una matriz con valores al azar con forma 3x3x3

In [80]:
arr7= np.random.randn(3,3,3)
arr7

array([[[ 0.82266813,  2.33032257, -0.36244078],
        [ 0.80016663, -0.39688448,  1.06451465],
        [-0.24930142,  1.79378667, -0.05158036]],

       [[ 2.17549583, -0.47519556,  0.30185991],
        [ 0.24228433,  0.6110176 , -1.71523403],
        [-0.62564104, -0.74500138, -1.38471097]],

       [[ 0.41223804, -0.75234723, -0.30907542],
        [ 0.25456646,  1.68439758, -0.69522188],
        [-1.23354185, -2.36455853, -0.69011127]]])

## Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [81]:
m= arr7.max()
mi= arr7.min()
print("este es el numero maximo: ",m)
print("este es el numero minimo: ",mi)

este es el numero maximo:  2.330322568945989
este es el numero minimo:  -2.364558530002239



## Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices

In [86]:
arr8= np.ones((10,10))
arr8[1:9,1:9]=0
arr8

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Crear la siguiente matriz utilizando la funcion arrange de Numpy (se puede utilizar la funcion reshape):

In [91]:
arr9= np.arange(0.01,1.01,0.01).reshape(10,10)
arr9

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [94]:
a = np.empty((5, 5))
for i in range(5):
    a[i] = i
a.T

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

## Obtener la suma de todos los valores de la matriz anterior

In [102]:
a.sum()

50.0

## Obtener los indices en los que el valor es el mismo para ambas matrices "M1 y M2":

In [105]:
M1=np.array([[1,2,3,4,5,6,7,8,9,10],[9,4,7,3,8,9,5,4,3,1]])
M2=np.array([[0,1,2,4,5,3,4,5,3,2],[9,2,3,4,8,5,1,7,8,9]])
M3=(M1==M2)
M1[M3]

array([4, 5, 9, 8])