In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49 (un vector con 40 valores que inicie en 10 y termine en 49)

In [11]:
data33 = np.arange(10, 50)
print(data33)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Invertir el vector anterior:

In [7]:
np.flip(data33)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [11]:
matrix = np.array ([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [9]:
maxit =  np.array((1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0))
np.where(maxit != 0)

(array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)

### Crear una matriz identidad de 6x6

In [12]:
matrix = np.eye (6)
print(matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Crear una matriz con valores al azar con forma 3x3x3

In [3]:
matrand = np.random.normal(size=((3, 3, 3)))
print(matrand)

[[[-0.85519269 -1.21978139 -0.70499733]
  [-0.65642615  1.551342    0.23728797]
  [ 0.98873093  0.46108911  1.13803016]]

 [[-1.20686456  0.21280135  0.56921739]
  [-0.32104058  0.64609941 -0.90258404]
  [-0.10898558 -0.91696083 -1.36593767]]

 [[ 1.28460703 -0.1110339   1.0808481 ]
  [ 0.97402545 -0.23333984 -0.20285169]
  [-0.33501338 -0.22411878  2.15463703]]]


### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [5]:
print ("El valor minimo es:", matrand.min(),"El valor maximo de la matriz es:", matrand.max())

El valor minimo es: -1.365937669809617 El valor maximo de la matriz es: 2.1546370316459322


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [15]:
matriz2 = np.ones([10, 10])
matriz2[1:9, 1:9]= 0
matriz2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Crear la siguiente matriz utilizando la funcion arange de Numpy (se puede utilizar la funcion reshape):

In [ ]:
#Ejemplo:
#           [[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
#            [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
#            [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
#            [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
#            [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
#            [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
#            [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
#            [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
#            [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
#            [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]]

In [26]:
matriznew = np.arange(0.01, 1.01, 0.01).reshape((10,10))

matriznew

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [ ]:
#Ejemplo del resultado:
#           [[0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4]])

In [58]:
matriz8 = np.random.rand(5, 5)
for i in range(5):
    for j in range(5):
        matriz8[i, j] = j
matriz8

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Obtener la suma de todos los valores de la matriz anterior:

In [61]:
matriz8.sum()

50.0

### Obtener los indices en los que el valor es el mismo para ambas matrices "M1 y M2"

In [67]:
M1=np.array([[1,2,3,4,5,6,7,8,9,10],[9,4,7,3,8,9,5,4,3,1]])
M2=np.array([[0,1,2,4,5,3,4,5,3,2],[9,2,3,4,8,5,1,7,8,9]])
# M1==M2

In [68]:
np.where(M1==M2)

(array([0, 0, 1, 1], dtype=int64), array([3, 4, 0, 4], dtype=int64))