Crear un vector con valores dentro del rango 10 a 49 (un vector con 40 valores que inicie en 10 y termine en 49)

In [10]:
import numpy as np
A = np.arange(10,50)
print(A)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Invertir el vector anterior:

In [16]:
print(A[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Crear una matriz 3x3 con valores de 0 a 8

In [17]:
B = np.array([(0,1,2,),(3,4,5),(6,7,8)])
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [43]:
C = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
C1 = np.array([])
Z = np.count_nonzero(C)
for i in C:
    if i != 0:
        C1 = np.append(C1, i)
print("Hay",Z , "numeros que no son 0")
print(C1)

Hay 11 numeros que no son 0
[ 1.  2.  4.  2.  4.  1. 12.  4.  5.  6.  7.]


Crear una matriz identidad de 6x6

In [46]:
D = np.identity(6)
print(D)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Crear una matriz con valores al azar con forma 3x3x3

In [47]:
E = np.random.random((3,3,3))
print(E)

[[[0.43469715 0.08745647 0.97536373]
  [0.75761341 0.67227717 0.28015889]
  [0.61006392 0.58129533 0.91879353]]

 [[0.77978241 0.92582376 0.12643115]
  [0.3533953  0.07366856 0.42921165]
  [0.17552864 0.19767374 0.50964002]]

 [[0.55664965 0.62380698 0.17244354]
  [0.28961056 0.12437097 0.06768346]
  [0.26300518 0.27296921 0.93337887]]]


Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [49]:
E1 = E.min()
E2 = E.max()
print("El valor minimo es",E1,"y el maximo es",E2)

El valor minimo es 0.0676834615336196 y el maximo es 0.9753637334434052


Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [52]:
F = np.ones((10,10))
F[1:-1,1:-1] = 0
print(F)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Crear la siguiente matriz utilizando la funcion arrange de Numpy (se puede utilizar la funcion reshape):

In [51]:
G = np.reshape(np.arange(0.01,1.01,0.01),(-1, 10))
print(G)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [64]:
H = np.empty((5,5))
for i in range(5):
    H[i] = i
print(H.T)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Obtener la suma de todos los valores de la matriz anterior:

In [65]:
H.sum()

50.0

Obtener los indices en los que el valor es el mismo para ambas matrices "M1 y M2":

In [66]:
M1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [9, 4, 7, 3, 8, 9, 5, 4, 3, 1]])
M2 = np.array([[0, 1, 2, 4, 5, 3, 4, 5, 3, 2], [9, 2, 3, 4, 8, 5, 1, 7, 8, 9]])
M3 = np.intersect1d(M1, M2)
print(M3)

[1 2 3 4 5 7 8 9]
