In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49 (un vector con 40 valores que inicie en 10 y termine en 49)

In [2]:
Vector = np.arange (10,50)
print (Vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Invertir el vector anterior:

In [6]:
Vector [::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [55]:
Matriz = np.arange (0,9).reshape ((3,3))
print (Matriz_1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [49]:
Data = np.array ([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
Indices = np.where (Data!=0)
Indices_1 = np.array([])
for i in Data:
    if i != 0:
        Indices_1 = np.append (Indices_1,i)
print ("Los indices que no son ceros en el arreglo son:",Indices, )
print ("Siendo estos los numeros:",Indices_1,)



Los indices que no son ceros en el arreglo son: (array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)
Siendo estos los numeros: [ 1.  2.  4.  2.  4.  1. 12.  4.  5.  6.  7.]


### Crear una matriz identidad de 6x6 

In [54]:
Matriz_2 = np.identity(6)
print (Matriz_2)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Crear una matriz con valores al azar con forma 3x3x3 

In [72]:
Matriz_3 = np.random.randn (3,3,3)
print (Matriz_3)


[[[-0.06944843 -0.37823171  0.69112292]
  [-0.32700217  1.63536988 -0.03698399]
  [ 0.48311481 -0.84824382  0.39732209]]

 [[ 2.13601289 -1.56936972 -1.37850134]
  [-0.83281718 -1.08533721 -0.5742064 ]
  [-0.18891665 -0.99818849 -0.79316409]]

 [[ 0.70646348  0.68375755 -0.70180333]
  [-0.58995133  0.13702399  1.74684482]
  [-1.75120057  0.12280145  1.98724022]]]


### Encontrar los indices de los valores minimos y maximos de la anterior matriz 

In [74]:
Minimo = np.min (Matriz_3)
print ("El valor minimo es:",Minimo)
Maximo = np.max (Matriz_3)
print ("El valor maximo es:",Maximo)

El valor minimo es: -1.7512005699264008
El valor maximo es: 2.1360128879586076


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices) 

In [79]:
Matriz_4 = np.ones((10,10))
Matriz_4 [1:-1,1:-1]= 0
print (Matriz_4)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Crear la siguiente matriz utilizando la funcion arrange de Numpy (se puede utilizar la funcion reshape):

In [83]:
Matriz_5 = np.arange (0.01,1.01,0.01).reshape(10,10)
print (Matriz_5)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4¶

In [94]:
Matriz_6 = np.empty((5,5))
for i in range(5):
    Matriz_6[i] = i
print (Matriz_6.T)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### Obtener la suma de todos los valores de la matriz anterior:

In [97]:
Suma = Matriz_6.sum()
print (Suma)

50.0


### Obtener los indices en los que el valor es el mismo para ambas matrices "M1 y M2":

In [133]:
M1=np.array([[1,2,3,4,5,6,7,8,9,10],[9,4,7,3,8,9,5,4,3,1]])
M2=np.array([[0,1,2,4,5,3,4,5,3,2],[9,2,3,4,8,5,1,7,8,9]])
Indices_3 = np.where (M1==M2)
print (Indices_3)


(array([0, 0, 1, 1], dtype=int64), array([3, 4, 0, 4], dtype=int64))
