In [3]:
# Ejecutar el siguiente comando en caso de no tener la libreria Numpy intalada:
#                                 !conda install numpy

In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49 (un vector con 40 valores que inicie en 10 y termine en 49)

In [3]:
matriz_1 = np.arange(10,50)

matriz_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Invertir el vector anterior:

In [6]:
np.flip(matriz_1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [15]:
matriz_2 = np.arange(9)
matriz_21 = np.reshape(matriz_2, (3,3))

matriz_21

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [201]:
matriz_3 = np.array((1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0))

np.where(matriz_3 == 0)



(array([ 5,  7,  8,  9, 15], dtype=int64),)

### Crear una matriz identidad de 6x6

In [4]:
matriz_ide = np.identity(6)

matriz_ide

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [36]:
matriz_ran = np.random.randn(3,3,3)

print(matriz_ran)


[[[-2.43244629 -0.26346693  0.58058461]
  [ 0.39126704  2.38520348  0.50213667]
  [ 0.50314351 -1.62319057  1.43664962]]

 [[ 0.04318005 -0.18807362 -2.06150337]
  [ 1.35996619 -0.39323191 -1.87343014]
  [-1.99544231 -0.63835347 -2.0044312 ]]

 [[-1.08446567  0.29414618  0.49422144]
  [ 0.52182926 -0.53124326  0.62464448]
  [ 1.70798287  1.08787602  0.60398936]]]


### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [41]:
print("Minimo: ", matriz_ran.min())
print("Maximo: ", matriz_ran.max())

Minimo:  -2.4324462907608533
Maximo:  2.3852034849150905


### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [5]:
#Ejemplo:
#           [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#            [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [139]:
matriz_4 = np.ones([10,10])
matriz_4[ 1:9 , 1:9 ] = 0

matriz_4

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Crear la siguiente matriz utilizando la funcion arange de Numpy (se puede utilizar la funcion reshape):

In [7]:
#Ejemplo:
#           [[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
#            [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
#            [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
#            [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
#            [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
#            [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
#            [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
#            [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
#            [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
#            [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]]

In [58]:
matriz_arr = np.arange(0.01,1.01,0.01).reshape((10,10))

matriz_arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [8]:
#Ejemplo del resultado:
#           [[0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4],
#            [0, 1, 2, 3, 4]])

In [167]:
matriz_5 = np.empty((5, 5))

for i in range(5):
    
    for j in range(5):
        
        matriz_5[i,j] = j
        
matriz_5

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Obtener la suma de todos los valores de la matriz anterior:

In [169]:
print(matriz_5.sum())

50.0


### Obtener los indices en los que el valor es el mismo para ambas matrices "M1 y M2":

In [200]:
M1=np.array([[1,2,3,4,5,6,7,8,9,10],[9,4,7,3,8,9,5,4,3,1]])
M2=np.array([[0,1,2,4,5,3,4,5,3,2],[9,2,3,4,8,5,1,7,8,9]])

np.where(M1 == M2)

(array([0, 0, 1, 1], dtype=int64), array([3, 4, 0, 4], dtype=int64))