**Crear un vector con numeros dentro del rango 10 a 49

In [1]:
import numpy as np 
a=np.arange(10,50,1)
print (a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Invertir el vector anterior**

In [3]:
import numpy as np
a=np.arange(49,9,-1)
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**Crear una matriz 3x3 con valores del 0 al 8**

In [12]:
import numpy as np
a=np.arange(9).reshape((3,3))


print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Encontrar indices que no son ceros en el arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

**Crear una matriz identidad 6x6**

In [13]:
a=np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


**Matriz con valores al azar 3x3x3**

In [17]:
a=np.random.rand(27).reshape(3,3,3)

print(a)

[[[0.52789015 0.30678923 0.2433222 ]
  [0.09064142 0.94636379 0.03134268]
  [0.94904383 0.95779326 0.55707435]]

 [[0.56861066 0.19509873 0.82057384]
  [0.16235822 0.27706255 0.19447486]
  [0.28575794 0.83658745 0.08030427]]

 [[0.14516487 0.45241866 0.954218  ]
  [0.52880005 0.2841963  0.33674505]
  [0.26583815 0.15663819 0.39375189]]]


**Encontrar valores maximos y minimos de la anterior matriz**

In [18]:
#La matriz anterior tiene numeros random por lo cual esta vez me va a arrojar dif valores debido a la funcion que estoy usando
a=np.random.rand(27).reshape(3,3,3)
vm=np.amin(a)
Vm=np.amax(a)
print(a)

print("el valor maximo es:",Vm)
print("el valor minimo es:",vm)

[[[0.70483124 0.11187354 0.17955724]
  [0.43901292 0.90123829 0.69483119]
  [0.73995933 0.53051561 0.02019456]]

 [[0.58329908 0.84372658 0.08181823]
  [0.84026435 0.31074136 0.00483228]
  [0.76848119 0.99646551 0.92344836]]

 [[0.79765934 0.88260045 0.20108038]
  [0.42978615 0.45037255 0.45421944]
  [0.80522839 0.03359794 0.3657283 ]]]
el valor maximo es: 0.9964655126900126
el valor minimo es: 0.004832282131301935


**Crear una matriz 10x10 con 1 a los bordes y 0 en el interior **

In [20]:
a=np.ones((10,10))
a[ 1:9, 1:9]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Crear la matriz correspondiente **

In [36]:
a=np.arange(0.01,1.01,0.01).reshape((10,10))

print (a)

#con la funcion "linspace"= np.linspace(0,1,100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


**Crear una matriz 5x5 con renglones qu vayan de 0 a 4**

In [40]:
a=np.arange(5)
bbbb=np.tile(a,(5,1))
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**Obtener la suma de la matriz anterior**

In [49]:
a=np.arange(5)
b=np.tile(a,(5,1))
print(b.sum())


50


**Obtener los indicies**

In [50]:
M1=np.array([[1,2,3,4,5,6,7,8,9,10],[9,4,7,3,8,9,5,4,3,1]])
M2=np.array([[0,1,2,4,5,3,4,5,3,2],[9,2,3,4,8,5,1,7,8,9]])
np.where(M1==M2)


(array([0, 0, 1, 1], dtype=int64), array([3, 4, 0, 4], dtype=int64))